### ISSUE TITLE
Expected training resources and evaluation code?

### ISSUE THREAD

**Issue by HuAndrew** [tomasjakab/imm#7]
Hi, Jakab, Ankush, Vedaldi

Thank you for sharing your great work "Unsupervised Learning of Object Landmarks through Conditional Image Generation" in NIPS2018. 

(1) I'd like to ask how long it would take to fully train a model on CelebA or ALFW.  
How much time and how many GPUS (platform) did it take you to train your model? 

(2) Could you please provide the "Legacy Training and Evaluation Code". I had sent email, but no message.

email: andrewhuhong@gmail.com

Thanks in advance!

**Comment by DuaneNielsen** [comment]
Hi Andrew,

A couple of us are also looking at replicating result.  We found this old issue helpful.

https://github.com/tomasjakab/imm/issues/1

Not a complete answer to your question, but hopefully it helps a bit.

**Comment by tomasjakab** [comment]
Hi Andrew,

(1) 100k-150k iterations should be enough. That is about 2-3 days on Nvidia GTX 1080 Ti

(2) I will share the legacy code with you but note that it is in MATLAB and it is not needed since we reimplemented everything in Python and made it part of this repo.

Let me know should you have more questions!

**Comment by HuAndrew** [comment]
I got it, thank you very much!

**Comment by HuAndrew** [comment]
Thank you for sharing, and I still want Matlab's evaluation code hopefully.
